import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("UI inspection seed script is wired and avoids real external providers", async () => {
  const pkg = JSON.parse(await readFile(new URL("../../package.json", import.meta.url), "utf8"));
  const source = await readFile(new URL("./seed-ui-inspection.ts", import.meta.url), "utf8").catch(() => "");

  assert.equal(pkg.scripts["seed:ui-inspection"], "tsx src/scripts/seed-ui-inspection.ts");
  assert.match(source, /UI_INSPECTION_MARKER/);
  assert.match(source, /ui_inspection_sample/);
  assert.match(source, /ensureUiInspectionProject/);
  assert.match(source, /seedStageStates/);
  assert.match(source, /seedBriefAndRisk/);
  assert.match(source, /seedCreativeAndCommercial/);
  assert.match(source, /seedScriptSetupAndStoryboard/);
  assert.match(source, /seedReviewCutsAndArchive/);
  assert.match(source, /storyboard_images/);
  assert.match(source, /storyboard_image_batches/);
  assert.match(source, /storyboard_image_batch_items/);
  assert.match(source, /storyboard_videos/);
  assert.match(source, /storyboard_video_generation_inputs/);
  assert.match(source, /review_cuts/);
  assert.match(source, /archive_records/);
  assert.match(source, /SAMPLE_VIDEO_URL/);
  assert.match(source, /from change_requests/);
  assert.doesNotMatch(source, /insert into change_requests[\s\S]*on conflict do nothing/);
  assert.match(source, /risk_check_cards/);
  assert.match(source, /creative_directions/);
  assert.match(source, /creative_proposal_rounds/);
  assert.match(source, /workload_estimates/);
  assert.match(source, /quotes/);
  assert.match(source, /contracts/);
  assert.match(source, /script_direction_packages/);
  assert.match(source, /production_entities/);
  assert.match(source, /production_reference_sets/);
  assert.match(source, /storyboard_scenes/);
  assert.match(source, /storyboard_shots/);
  assert.match(source, /current_stage = 'settlement_delivery_archive'/);
  assert.doesNotMatch(source, /generateOpenAIImage/);
  assert.doesNotMatch(source, /callArk/);
  assert.doesNotMatch(source, /deliverToFeishu/);
});
